[book]
title = "Projektowanie Aplikacji"
authors = ["Krystian Wiecheć"]
description = "Praca kreatywna o projektowaniu aplikacji na lekcję projektowania oprogramowania."
language = "pl"

[build]
build-dir = "build"
create-missing = false

[output.html]
mathjax-support = true
default-theme = "coal"
preferred-dark-theme = "coal"
